### ISSUE TITLE
awx web container couldn't start when postgresql persistent storage is disabled

### ISSUE THREAD

**Issue by beanallergy** [arthur-c/ansible-awx-helm-chart#2]
Hi,

First of all thanks for the chart! I downloaded the directory awx and followed your instructions, only changed "postgresql.persistence.enabled = false" in values.yaml. "Web" container couldn't start in awx pod, with the following logs 
`~/ansible-awx-helm-chart$ kubectl logs -n awx awx-76859f59c4-k9tcf web
Using /etc/ansible/ansible.cfg as config file
127.0.0.1 | SUCCESS => {
    "changed": false,
    "elapsed": 0,
    "path": null,
    "port": 5432,
    "search_regex": null,
    "state": "started"
}
Using /etc/ansible/ansible.cfg as config file
127.0.0.1 | SUCCESS => {
    "changed": false,
    "elapsed": 0,
    "path": null,
    "port": 11211,
    "search_regex": null,
    "state": "started"
}
Using /etc/ansible/ansible.cfg as config file
127.0.0.1 | SUCCESS => {
    "changed": false,
    "elapsed": 0,
    "path": null,
    "port": 5672,
    "search_regex": null,
    "state": "started"
}
Using /etc/ansible/ansible.cfg as config file`

Only other errors I could find is in postgresql pod logs, about some non-existing relations
`~/ansible-awx-helm-chart$ kubectl logs -n awx awx-postgresql-0
Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
postgre INFO  ==> Creating database awx...
postgre INFO  ==> Creating postgres user with unrestricted access...
postgre INFO  ==> Configuring PostgreSQL...
postgre INFO  ==> Configuring replication parameters...
postgre INFO  ==> Configuring permissions for config files...
postgre INFO
postgre INFO  ########################################################################
postgre INFO   Installation parameters for postgresql:
postgre INFO     Root User: postgres
postgre INFO     Password: **********
postgre INFO     Database: awx
postgre INFO   (Passwords are not shown for security reasons)
postgre INFO  ########################################################################
postgre INFO
nami    INFO  postgresql successfully initialized
INFO  ==> Starting postgresql...
LOG:  autovacuum launcher started
LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2019-01-04 07:33:22 GMT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  incomplete startup packet
LOG:  incomplete startup packet
LOG:  incomplete startup packet
ERROR:  relation "conf_setting" does not exist at character 158
STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."user_id" IS NULL AND "conf_setting"."key" IN ('SOCIAL_AUTH_GOOGLE_OAUTH2_ORGANIZATION_MAP', 'LICENSE', 'SOCIAL_AUTH_GITHUB_TEAM_MAP', 'AUTH_LDAP_5_GROUP_TYPE_PARAMS', 'SOCIAL_AUTH_GITHUB_ORG_NAME', 'AUTH_LDAP_5_USER_DN_TEMPLATE', 'AWX_PROOT_SHOW_PATHS', 'SOCIAL_AUTH_GITHUB_SECRET', 'AUTH_LDAP_5_REQUIRE_GROUP', 'AUTH_LDAP_2_GROUP_SEARCH', 'AUTH_LDAP_1_GROUP_SEARCH', 'AUTH_LDAP_4_DENY_GROUP', 'AUTH_LDAP_5_TEAM_MAP', 'LOG_AGGREGATOR_LOGGERS', 'SOCIAL_AUTH_SAML_ORGANIZATION_MAP', 'AUTH_LDAP_4_GROUP_TYPE', 'AUTH_LDAP_1_GROUP_TYPE', 'LOG_AGGREGATOR_PROTOCOL', 'AUTH_LDAP_1_BIND_DN', 'ORG_ADMINS_CAN_SEE_ALL_USERS', 'MAX_UI_JOB_EVENTS', 'AUTH_LDAP_4_USER_ATTR_MAP', 'AUTH_BASIC_ENABLED', 'SOCIAL_AUTH_GITHUB_TEAM_ORGANIZATION_MAP', 'TOWER_URL_BASE', 'AUTH_LDAP_4_USER_FLAGS_BY_GROUP', 'AUTH_LDAP_3_DENY_GROUP', 'AUTH_LDAP_4_USER_DN_TEMPLATE', 'SOCIAL_AUTH_SAML_SP_ENTITY_ID', 'SOCIAL_AUTH_SAML_SECURITY_CONFIG', 'AUTH_LDAP_1_TEAM_MAP', 'SOCIAL_AUTH_ORGANIZATION_MAP', 'AUTH_LDAP_3_GROUP_TYPE', 'EVENT_STDOUT_MAX_BYTES_DISPLAY', 'AUTH_LDAP_5_GROUP_SEARCH', 'AUTH_LDAP_3_START_TLS', 'ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC', 'AUTH_LDAP_4_USER_SEARCH', 'AUTH_LDAP_3_CONNECTION_OPTIONS', 'SOCIAL_AUTH_GITHUB_ORG_SECRET', 'AWX_ISOLATED_CONNECTION_TIMEOUT', 'TACACSPLUS_SESSION_TIMEOUT', 'AUTH_LDAP_3_USER_FLAGS_BY_GROUP', 'AUTH_LDAP_3_USER_SEARCH', 'TACACSPLUS_HOST', 'RADIUS_PORT', 'AUTH_LDAP_2_REQUIRE_GROUP', 'AUTH_LDAP_2_USER_DN_TEMPLATE', 'AWX_ISOLATED_KEY_GENERATION', 'AUTH_LDAP_2_BIND_PASSWORD', 'AUTH_LDAP_1_DENY_GROUP', 'LOG_AGGREGATOR_HOST', 'AUTH_LDAP_1_BIND_PASSWORD', 'AWX_ISOLATED_PRIVATE_KEY', 'AUTH_LDAP_4_START_TLS', 'AUTH_LDAP_5_USER_SEARCH', 'AUTH_LDAP_GROUP_TYPE', 'AUTH_LDAP_3_BIND_PASSWORD', 'AUTH_LDAP_5_BIND_PASSWORD', 'SESSION_COOKIE_AGE', 'SOCIAL_AUTH_TEAM_MAP', 'AUTH_LDAP_1_USER_DN_TEMPLATE', 'LOG_AGGREGATOR_INDIVIDUAL_FACTS', 'AUTH_LDAP_4_GROUP_TYPE_PARAMS', 'SOCIAL_AUTH_GOOGLE_OAUTH2_TEAM_MAP', 'SESSIONS_PER_USER', 'SOCIAL_AUTH_SAML_SUPPORT_CONTACT', 'OAUTH2_PROVIDER', 'AWX_ROLES_ENABLED', 'AUTH_LDAP_2_ORGANIZATION_MAP', 'SOCIAL_AUTH_GITHUB_TEAM_KEY', 'AUTH_LDAP_3_USER_DN_TEMPLATE', 'AUTH_LDAP_REQUIRE_GROUP', 'AUTH_LDAP_2_USER_ATTR_MAP', 'AUTH_LDAP_5_ORGANIZATION_MAP', 'AUTH_LDAP_3_SERVER_URI', 'SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET', 'AUTH_LDAP_2_BIND_DN', 'AUTH_LDAP_1_GROUP_TYPE_PARAMS', 'AUTH_LDAP_5_START_TLS', 'SOCIAL_AUTH_SAML_ORG_INFO', 'UI_LIVE_UPDATES_ENABLED', 'SOCIAL_AUTH_SAML_TEAM_ATTR', 'AUTH_LDAP_USER_SEARCH', 'SOCIAL_AUTH_AZUREAD_OAUTH2_KEY', 'AUTH_LDAP_2_CONNECTION_OPTIONS', 'LOG_AGGREGATOR_PORT', 'LOG_AGGREGATOR_TCP_TIMEOUT', 'AUTH_LDAP_2_USER_FLAGS_BY_GROUP', 'AUTH_LDAP_5_DENY_GROUP', 'TACACSPLUS_PORT', 'SOCIAL_AUTH_GOOGLE_OAUTH2_KEY', 'PROXY_IP_WHITELIST', 'AUTH_LDAP_3_GROUP_SEARCH', 'AUTH_LDAP_BIND_DN', 'SOCIAL_AUTH_GITHUB_TEAM_ID', 'LOG_AGGREGATOR_LEVEL', 'PENDO_TRACKING_STATE', 'DEFAULT_PROJECT_UPDATE_TIMEOUT', 'SOCIAL_AUTH_SAML_EXTRA_DATA', 'SOCIAL_AUTH_SAML_SP_EXTRA', 'AUTH_LDAP_USER_FLAGS_BY_GROUP', 'SOCIAL_AUTH_USER_FIELDS', 'AUTH_LDAP_1_USER_ATTR_MAP', 'AUTH_LDAP_4_REQUIRE_GROUP', 'AUTH_LDAP_2_DENY_GROUP', 'SOCIAL_AUTH_GITHUB_ORGANIZATION_MAP', 'TACACSPLUS_SECRET', 'AUTH_LDAP_5_USER_ATTR_MAP', 'SOCIAL_AUTH_GITHUB_ORG_TEAM_MAP', 'LOG_AGGREGATOR_ENABLED', 'ALLOW_OAUTH2_FOR_EXTERNAL_USERS', 'TACACSPLUS_AUTH_PROTOCOL', 'SOCIAL_AUTH_SAML_TECHNICAL_CONTACT', 'AUTH_LDAP_GROUP_SEARCH', 'AWX_ISOLATED_PUBLIC_KEY', 'AUTH_LDAP_2_GROUP_TYPE', 'SOCIAL_AUTH_SAML_ENABLED_IDPS', 'ALLOW_JINJA_IN_EXTRA_VARS', 'AWX_ISOLATED_CHECK_INTERVAL', 'SOCIAL_AUTH_SAML_TEAM_MAP', 'AUTH_LDAP_3_ORGANIZATION_MAP', 'AWX_PROOT_HIDE_PATHS', 'AUTH_LDAP_USER_DN_TEMPLATE', 'AUTH_LDAP_ORGANIZATION_MAP', 'AUTH_LDAP_3_TEAM_MAP', 'AUTH_LDAP_1_CONNECTION_OPTIONS', 'AUTH_LDAP_4_SERVER_URI', 'CUSTOM_LOGIN_INFO', 'AWX_PROOT_BASE_PATH', 'TOWER_ADMIN_ALERTS', 'LOG_AGGREGATOR_PASSWORD', 'SOCIAL_AUTH_GITHUB_TEAM_SECRET', 'AUTH_LDAP_5_BIND_DN', 'AUTH_LDAP_5_GROUP_TYPE', 'STDOUT_MAX_BYTES_DISPLAY', 'AUTH_LDAP_CONNECTION_OPTIONS', 'AUTH_LDAP_2_START_TLS', 'AUTH_LDAP_1_USER_SEARCH', 'SOCIAL_AUTH_SAML_SP_PRIVATE_KEY', 'AUTH_LDAP_1_START_TLS', 'AUTH_LDAP_TEAM_MAP', 'LOG_AGGREGATOR_VERIFY_CERT', 'MANAGE_ORGANIZATION_AUTH', 'AUTH_LDAP_2_SERVER_URI', 'SCHEDULE_MAX_JOBS', 'AUTH_LDAP_BIND_PASSWORD', 'AUTH_LDAP_4_CONNECTION_OPTIONS', 'AUTH_LDAP_4_GROUP_SEARCH', 'AUTH_LDAP_USER_ATTR_MAP', 'AUTH_LDAP_5_CONNECTION_OPTIONS', 'CUSTOM_LOGO', 'SOCIAL_AUTH_AZUREAD_OAUTH2_TEAM_MAP', 'LOG_AGGREGATOR_USERNAME', 'AUTH_LDAP_DENY_GROUP', 'AUTH_LDAP_4_ORGANIZATION_MAP', 'SOCIAL_AUTH_GITHUB_KEY', 'AUTH_LDAP_1_ORGANIZATION_MAP', 'SOCIAL_AUTH_SAML_ORGANIZATION_ATTR', 'SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS', 'SOCIAL_AUTH_GITHUB_ORG_ORGANIZATION_MAP', 'AUTH_LDAP_1_SERVER_URI', 'AWX_ISOLATED_LAUNCH_TIMEOUT', 'AUTH_LDAP_1_USER_FLAGS_BY_GROUP', 'AWX_TASK_ENV', 'DEFAULT_JOB_TIMEOUT', 'AUTH_LDAP_2_USER_SEARCH', 'AUTH_LDAP_2_TEAM_MAP', 'AD_HOC_COMMANDS', 'AUTH_LDAP_3_BIND_DN', 'AUTH_LDAP_3_USER_ATTR_MAP', 'AUTH_LDAP_4_TEAM_MAP', 'SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS', 'RADIUS_SECRET', 'RADIUS_SERVER', 'AUTH_LDAP_SERVER_URI', 'AUTH_LDAP_1_REQUIRE_GROUP', 'AUTH_LDAP_4_BIND_PASSWORD', 'AUTH_LDAP_GROUP_TYPE_PARAMS', 'LOG_AGGREGATOR_TOWER_UUID', 'AUTH_LDAP_2_GROUP_TYPE_PARAMS', 'AUTH_LDAP_5_SERVER_URI', 'SOCIAL_AUTH_GITHUB_ORG_KEY', 'ACTIVITY_STREAM_ENABLED', 'AWX_ANSIBLE_CALLBACK_PLUGINS', 'SOCIAL_AUTH_GITHUB_TEAM_TEAM_MAP', 'ANSIBLE_FACT_CACHE_TIMEOUT', 'DEFAULT_INVENTORY_UPDATE_TIMEOUT', 'AUTH_LDAP_5_USER_FLAGS_BY_GROUP', 'AUTH_LDAP_3_REQUIRE_GROUP', 'AUTH_LDAP_START_TLS', 'AUTH_LDAP_3_GROUP_TYPE_PARAMS', 'SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET', 'LOG_AGGREGATOR_TYPE', 'AUTH_LDAP_4_BIND_DN', 'SOCIAL_AUTH_SAML_SP_PUBLIC_CERT', 'SOCIAL_AUTH_AZUREAD_OAUTH2_ORGANIZATION_MAP')) ORDER BY "conf_setting"."id" ASC
ERROR:  relation "django_migrations" does not exist at character 124
LOG:  incomplete startup packet `

Is this expected when you're disabling persistent storage? I installed using the official playbook from https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/tasks/main.yml before and it wasn't a problem, but it would be nice to get a Helm installer

**Comment by beanallergy** [comment]
I think what's needed is database migration job to follow the steps from AWX official installer https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/templates/management-pod.yml.j2 . Otherwise postgresql database is not set up properly...

Closing this issue because I have my own Helm chart working now.

**Comment by fr34k8** [comment]
@karen-nguyen could you share the helm chart ?
