### ISSUE TITLE
pls up date to awx 3.0.1 

### ISSUE THREAD

**Issue by macaty** [arthur-c/ansible-awx-helm-chart#3]
pls up date to awx 3.0.1  
thx

**Comment by aleks-mariusz** [comment]
curious, have you tried updating the image tag to 3.0.1 (btw there's [newer version now](https://github.com/ansible/awx/releases) e.g .4.0.0 being latest at the time of this post), and did that work on its own (meaning you merely asking that it picks that one by default?) or did something change about the way it needs to be deployed that makes this request a bit more involved?

**Comment by ghost** [comment]
> pls up date to awx 3.0.1
> thx

You can use 4.0.0, you just need to change the tag and replace file() function with open() (python3) in config map. The resulting line would look like follows:
    SECRET_KEY = open('/etc/tower/SECRET_KEY', 'rb').read().strip()

**Comment by pratibhadeepti** [comment]
Hi @def0def0 any idea how can I update pip package like boto3 or botocore on version 6.1.0 using ansible 2.8.2, if I'm using sudo to install package getting access denied.

Thanks

**Comment by mjallday** [comment]
I successfully launched 9.1.1 using #10.
